### ISSUE TITLE
Events not making it to Mixpanel

### ISSUE THREAD

**Issue by bstillitano** [segment-integrations/analytics-swift-mixpanel#3]
It would appear that since migrating from the obj-c library to this one, our events no longer make it through to mixpanel. They make it to segment, and segement reports that they are succesfully delivered to mixpanel, however the events never show up. Integration code is below:

```
let configuration: Configuration = Configuration(writeKey: "WRITE_KEY_OBFUSCATED")
            .trackApplicationLifecycleEvents(true)
            .trackDeeplinks(true)
        let analytics: Analytics = Analytics(configuration: configuration)
        analytics.add(plugin: BrazeDestination())
        analytics.add(plugin: MixpanelDestination())
        await Metrics.instance.setProvider(analytics)
```

**Comment by alanjcharles** [comment]
Hi @bstillitano, sorry to hear you're running into issues.

Are you attempting to send events to Mixpanel via a Cloud Mode connection or via a Device Mode connection? 

I ask because if you are using a Device Mode connection, your setup looks generally correct. However, you would not be able to use Segment workspace features you mention like the Event Delivery Dashboard as we have no record of Device Mode events once they are handed off to the partner sdk. If you intend to use a Cloud Mode connection, you can remove  `analytics.add(plugin: MixpanelDestination())` 

If you are attempting to use Mixpanel with a Device Mode connection, have you been able to verify that the Mixpanel SDK is actually sending data as you'd expect? 

This is typically possible by using a [partner SDK's logging functionality ](https://github.com/mixpanel/mixpanel-swift#faq)

Happy to look into this further once I you're able to provide some additional context. Thanks!
