### ISSUE TITLE
Default Mobile Events Collection Lost 

### ISSUE THREAD

**Issue by eyalgofer** [segment-integrations/analytics-swift-mixpanel#5]
We lost all of our Mobile Events (First App Open, App Updated, App Session, etc..) after update 1.1.3 -> 1.1.4
downgraded to 1.1.3 until resolved.

**Comment by alanjcharles** [comment]
Hi @eyalgofer sorry to hear you're running into issues. The only change we made between `1.1.3` and `1.1.4` is to set `trackAutomaticEvents` to false in the Mixpanel initialization method. We set it to false because it seems Mixpanel is sunsetting this functionality for various reasons (namely security) and don't have any plans to change that currently. Please refer to [this Mixpanel post](https://mixpanel.com/blog/update-autotrack-data-collection/) about it for more information. Feel free to reach out here or to friends@segment.com if you have additional information we're missing or concerns we may not have accounted for. Thanks!
